### ISSUE TITLE
Spell toolbar button is not appearing

### ISSUE THREAD

**Issue by Lord451125** [Vek17/WrathMods-TabletopTweaks#145]
**Describe the bug**
Unable to cast spells after the newest patch, 1.07c.

When viewing the buttons above the toolbar, the S/A/B, the S is missing and it displays the actions for the incorrect character.    

Happens in all games I have running Tabletop Tweaks.  

Created a new game with all mods, button missing.  
Created one with no mods, button was there as expected.  
Created one with all other mods except Tabletop Tweaks and the button was there again.  

Currently using mods:
Inventory Searchbar
Mythic Spellbook Tweak 
Pathfinder Autobuff 
Respect Mod
Toybox
Weapon Focus Plus

**Comment by livercat** [comment]
This seems to be a relevant part from the extended log:
```
NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) Kingmaker.UI.MVVM._VM.ActionBar.ActionBarVM.Kingmaker.UI.MVVM._VM.ActionBar.ActionBarVM.CollectSpells_Patch0(Kingmaker.UI.MVVM._VM.ActionBar.ActionBarVM,Kingmaker.EntitySystem.Entities.UnitEntityData)
  at Kingmaker.UI.MVVM._VM.ActionBar.ActionBarVM.OnUnitChanged (Kingmaker.EntitySystem.Entities.UnitEntityData unit) [0x0006c] in <bc82b4888fc34731aeb2a6970622932b>:0 
  at UniRx.Observer+Subscribe`1[T].OnNext (T value) [0x00008] in <4ad2600184c1483d83823f25ad415b26>:0 
  at UniRx.ObserverNode`1[T].OnNext (T value) [0x00000] in <4ad2600184c1483d83823f25ad415b26>:0 
  at UniRx.ReactiveProperty`1[T].RaiseOnNext (T& value) [0x00009] in <4ad2600184c1483d83823f25ad415b26>:0 
  at UniRx.ReactiveProperty`1[T].set_Value (T value) [0x00024] in <4ad2600184c1483d83823f25ad415b26>:0 
  at Kingmaker.UI.MVVM._VM.ActionBar.ActionBarVM.UpdateSelection () [0x0002d] in <bc82b4888fc34731aeb2a6970622932b>:0 
  at Kingmaker.UI.MVVM._VM.ActionBar.ActionBarVM.OnUpdateHandler () [0x00025] in <bc82b4888fc34731aeb2a6970622932b>:0 
  at Kingmaker.UI.MVVM._VM.ActionBar.ActionBarVM.<.ctor>b__21_0 (UniRx.Unit _) [0x00000] in <bc82b4888fc34731aeb2a6970622932b>:0 
  at UniRx.Observer+Subscribe`1[T].OnNext (T value) [0x00008] in <4ad2600184c1483d83823f25ad415b26>:0 
  at UniRx.InternalUtil.ListObserver`1[T].OnNext (T value) [0x00010] in <4ad2600184c1483d83823f25ad415b26>:0 
  at UniRx.Subject`1[T].OnNext (T value) [0x00000] in <4ad2600184c1483d83823f25ad415b26>:0 
  at UniRx.MainThreadDispatcher.Update () [0x00013] in <4ad2600184c1483d83823f25ad415b26>:0 
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
UniRx.<>c:<.ctor>b__52_0(Exception)
UniRx.MainThreadDispatcher:Update()
 
(Filename: <bc82b4888fc34731aeb2a6970622932b> Line: 0)


```

**Comment by OverkillEngine2021** [comment]
Found a workaround posted for this on Reddit:

> you can fix it with editing file "Fixes.json"
> 
> Disable arcanist PreparedSpellUI in TTT
> 
> \Mods\TabletopTweaks\UserSettings -> Fixes.json -> Arcanist > "PreparedSpellUI": false

Tested it and it appears to work.

**Comment by Vek17** [comment]
This should be fixed in 1.3.6

**Comment by GFreenD** [comment]
> This should be fixed in 1.3.6

this seems it have fixed on 1.3.6 yes maybe i got a bit confused at some trial and error testing i was doing im sorry,
yes i can confirm that you can access bars normally on 1.3.6 but i still cant rightclick on cantrips (0lv spells) to use as main action.
[Quick2.zip](https://github.com/Vek17/WrathMods-TabletopTweaks/files/7258747/Quick2.zip)
